import { apiClient } from "./client";

const ENDPOINT = "api/tasks";
const MEMBERS_ENDPOINT = "api/members";

// Types
export type TaskType =
  | "ONBOARDING_CALL"
  | "RENEWAL_FOLLOWUP"
  | "PAYMENT_COLLECTION"
  | "RETENTION_OUTREACH"
  | "WIN_BACK"
  | "GENERAL_FOLLOWUP"
  | "TOUR_SCHEDULED"
  | "TRIAL_FOLLOWUP"
  | "FEEDBACK_CALL"
  | "UPSELL_OPPORTUNITY";

export type TaskPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";

export type TaskStatus = "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "SNOOZED";

export type TaskOutcome =
  | "SUCCESSFUL"
  | "UNSUCCESSFUL"
  | "NO_ANSWER"
  | "RESCHEDULED"
  | "CANCELLED"
  | "LEFT_MESSAGE"
  | "MEMBER_DECLINED"
  | "MEMBER_CONVERTED";

export interface MemberTask {
  id: string;
  memberId: string;
  memberName?: string;
  taskType: TaskType;
  title: string;
  description?: string;
  dueDate?: string;
  dueTime?: string;
  priority: TaskPriority;
  status: TaskStatus;
  assignedToUserId?: string;
  assignedToName?: string;
  completedAt?: string;
  completedByUserId?: string;
  outcome?: TaskOutcome;
  outcomeNotes?: string;
  autoGenerated: boolean;
  source?: string;
  isOverdue: boolean;
  isDueToday: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTaskRequest {
  memberId: string;
  taskType: TaskType;
  title: string;
  description?: string;
  dueDate?: string;
  dueTime?: string;
  priority?: TaskPriority;
  assignedToUserId?: string;
  metadata?: Record<string, unknown>;
}

export interface UpdateTaskRequest {
  title?: string;
  description?: string;
  dueDate?: string;
  dueTime?: string;
  priority?: TaskPriority;
  assignedToUserId?: string;
}

export interface CompleteTaskRequest {
  outcome: TaskOutcome;
  notes?: string;
}

export interface SnoozeTaskRequest {
  newDueDate: string;
}

export interface RescheduleTaskRequest {
  newDueDate: string;
  newDueTime?: string;
}

export interface AssignTaskRequest {
  assigneeUserId: string;
}

export interface TaskStats {
  totalPending: number;
  totalInProgress: number;
  totalOverdue: number;
  totalDueToday: number;
  completedThisWeek: number;
}

export interface MyTasksResponse {
  stats: TaskStats;
  overdue: MemberTask[];
  dueToday: MemberTask[];
  upcoming: MemberTask[];
}

export interface PageResponse<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  page: number;
  size: number;
}

// API Functions

/**
 * Create a new task
 */
export async function createTask(request: CreateTaskRequest): Promise<MemberTask> {
  return apiClient.post(ENDPOINT, { json: request }).json();
}

/**
 * Get a task by ID
 */
export async function getTask(taskId: string): Promise<MemberTask> {
  return apiClient.get(`${ENDPOINT}/${taskId}`).json();
}

/**
 * Update a task
 */
export async function updateTask(
  taskId: string,
  request: UpdateTaskRequest
): Promise<MemberTask> {
  return apiClient.put(`${ENDPOINT}/${taskId}`, { json: request }).json();
}

/**
 * Assign a task
 */
export async function assignTask(
  taskId: string,
  request: AssignTaskRequest
): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/assign`, { json: request }).json();
}

/**
 * Unassign a task
 */
export async function unassignTask(taskId: string): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/unassign`).json();
}

/**
 * Start a task
 */
export async function startTask(taskId: string): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/start`).json();
}

/**
 * Complete a task
 */
export async function completeTask(
  taskId: string,
  request: CompleteTaskRequest
): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/complete`, { json: request }).json();
}

/**
 * Cancel a task
 */
export async function cancelTask(taskId: string, reason?: string): Promise<MemberTask> {
  const params = reason ? `?reason=${encodeURIComponent(reason)}` : "";
  return apiClient.post(`${ENDPOINT}/${taskId}/cancel${params}`).json();
}

/**
 * Snooze a task
 */
export async function snoozeTask(
  taskId: string,
  request: SnoozeTaskRequest
): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/snooze`, { json: request }).json();
}

/**
 * Reschedule a task
 */
export async function rescheduleTask(
  taskId: string,
  request: RescheduleTaskRequest
): Promise<MemberTask> {
  return apiClient.post(`${ENDPOINT}/${taskId}/reschedule`, { json: request }).json();
}

/**
 * Get tasks for a member
 */
export async function getMemberTasks(
  memberId: string,
  params?: {
    statuses?: TaskStatus[];
    page?: number;
    size?: number;
  }
): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  if (params?.statuses && params.statuses.length > 0) {
    params.statuses.forEach((status) => searchParams.append("statuses", status));
  }
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  const query = searchParams.toString();
  return apiClient.get(`${MEMBERS_ENDPOINT}/${memberId}/tasks${query ? `?${query}` : ""}`).json();
}

/**
 * Get my tasks (assigned to current user)
 */
export async function getMyTasks(params?: {
  statuses?: TaskStatus[];
  page?: number;
  size?: number;
}): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  if (params?.statuses && params.statuses.length > 0) {
    params.statuses.forEach((status) => searchParams.append("statuses", status));
  }
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  const query = searchParams.toString();
  return apiClient.get(`${ENDPOINT}/my-tasks${query ? `?${query}` : ""}`).json();
}

/**
 * Get my tasks for today (dashboard widget)
 */
export async function getMyTasksToday(): Promise<MyTasksResponse> {
  return apiClient.get(`${ENDPOINT}/my-tasks/today`).json();
}

/**
 * Get my tasks for a specific date
 */
export async function getMyTasksForDate(
  date: string,
  params?: {
    page?: number;
    size?: number;
  }
): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  searchParams.set("date", date);
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  return apiClient.get(`${ENDPOINT}/my-tasks/by-date?${searchParams.toString()}`).json();
}

/**
 * Get overdue tasks
 */
export async function getOverdueTasks(params?: {
  page?: number;
  size?: number;
}): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  const query = searchParams.toString();
  return apiClient.get(`${ENDPOINT}/overdue${query ? `?${query}` : ""}`).json();
}

/**
 * Get unassigned tasks
 */
export async function getUnassignedTasks(params?: {
  page?: number;
  size?: number;
}): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  const query = searchParams.toString();
  return apiClient.get(`${ENDPOINT}/unassigned${query ? `?${query}` : ""}`).json();
}

/**
 * Get tasks by type
 */
export async function getTasksByType(
  taskType: TaskType,
  params?: {
    page?: number;
    size?: number;
  }
): Promise<PageResponse<MemberTask>> {
  const searchParams = new URLSearchParams();
  if (params?.page !== undefined) searchParams.set("page", params.page.toString());
  if (params?.size !== undefined) searchParams.set("size", params.size.toString());

  const query = searchParams.toString();
  return apiClient.get(`${ENDPOINT}/by-type/${taskType}${query ? `?${query}` : ""}`).json();
}

/**
 * Get task statistics
 */
export async function getTaskStats(): Promise<TaskStats> {
  return apiClient.get(`${ENDPOINT}/stats`).json();
}

/**
 * Get available task types
 */
export async function getTaskTypes(): Promise<TaskType[]> {
  return apiClient.get(`${ENDPOINT}/types`).json();
}
