package com.liyaqa.platform.monitoring.model

enum class PlatformAuditAction {
    // Auth
    USER_LOGIN, USER_LOGOUT, PASSWORD_CHANGE, PASSWORD_RESET,
    // Team
    TEAM_MEMBER_INVITED, TEAM_MEMBER_ACTIVATED, TEAM_ROLE_CHANGED, TEAM_MEMBER_DEACTIVATED,
    // Client/Tenant
    CLIENT_CREATED, CLIENT_ACTIVATED, CLIENT_SUSPENDED, CLIENT_ARCHIVED,
    // Subscriptions
    SUBSCRIPTION_CREATED, SUBSCRIPTION_ACTIVATED, SUBSCRIPTION_CANCELLED, SUBSCRIPTION_RENEWED,
    // Deals
    DEAL_CREATED, DEAL_STAGE_CHANGED, DEAL_WON, DEAL_LOST,
    // Invoices
    INVOICE_CREATED, INVOICE_PAID, INVOICE_VOIDED,
    // Impersonation
    IMPERSONATION_STARTED, IMPERSONATION_ENDED,
    // API Keys
    API_KEY_CREATED, API_KEY_REVOKED, API_KEY_ROTATED,
    // System
    SETTINGS_CHANGED, EXPORT_REQUESTED, BULK_OPERATION, SYSTEM_EVENT
}

enum class PlatformAuditActorType {
    PLATFORM_USER, SYSTEM, SCHEDULED_JOB
}

enum class PlatformAuditResourceType {
    PLATFORM_USER, CLIENT, SUBSCRIPTION, DEAL, INVOICE,
    SUPPORT_TICKET, API_KEY, IMPERSONATION_SESSION, SETTINGS, SYSTEM
}
