package com.liyaqa.membership.api

import com.liyaqa.membership.application.services.TaskStats
import com.liyaqa.membership.domain.model.MemberTask
import com.liyaqa.membership.domain.model.TaskOutcome
import com.liyaqa.membership.domain.model.TaskPriority
import com.liyaqa.membership.domain.model.TaskStatus
import com.liyaqa.membership.domain.model.TaskType
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.util.UUID

data class CreateTaskRequest(
    @field:NotNull(message = "Member ID is required")
    val memberId: UUID,

    @field:NotNull(message = "Task type is required")
    val taskType: TaskType,

    @field:NotBlank(message = "Title is required")
    val title: String,

    val description: String? = null,
    val dueDate: LocalDate? = null,
    val dueTime: LocalTime? = null,
    val priority: TaskPriority = TaskPriority.MEDIUM,
    val assignedToUserId: UUID? = null,
    val metadata: Map<String, Any>? = null
)

data class UpdateTaskRequest(
    val title: String? = null,
    val description: String? = null,
    val dueDate: LocalDate? = null,
    val dueTime: LocalTime? = null,
    val priority: TaskPriority? = null,
    val assignedToUserId: UUID? = null
)

data class CompleteTaskRequest(
    @field:NotNull(message = "Outcome is required")
    val outcome: TaskOutcome,

    val notes: String? = null
)

data class SnoozeTaskRequest(
    @field:NotNull(message = "New due date is required")
    val newDueDate: LocalDate
)

data class RescheduleTaskRequest(
    @field:NotNull(message = "New due date is required")
    val newDueDate: LocalDate,

    val newDueTime: LocalTime? = null
)

data class AssignTaskRequest(
    @field:NotNull(message = "Assignee user ID is required")
    val assigneeUserId: UUID
)

data class MemberTaskResponse(
    val id: UUID,
    val memberId: UUID,
    val memberName: String?,
    val taskType: TaskType,
    val title: String,
    val description: String?,
    val dueDate: LocalDate?,
    val dueTime: LocalTime?,
    val priority: TaskPriority,
    val status: TaskStatus,
    val assignedToUserId: UUID?,
    val assignedToName: String?,
    val completedAt: Instant?,
    val completedByUserId: UUID?,
    val outcome: TaskOutcome?,
    val outcomeNotes: String?,
    val autoGenerated: Boolean,
    val source: String?,
    val isOverdue: Boolean,
    val isDueToday: Boolean,
    val createdAt: Instant,
    val updatedAt: Instant
) {
    companion object {
        fun from(task: MemberTask, memberName: String? = null, assignedToName: String? = null): MemberTaskResponse = MemberTaskResponse(
            id = task.id,
            memberId = task.memberId,
            memberName = memberName,
            taskType = task.taskType,
            title = task.title,
            description = task.description,
            dueDate = task.dueDate,
            dueTime = task.dueTime,
            priority = task.priority,
            status = task.status,
            assignedToUserId = task.assignedToUserId,
            assignedToName = assignedToName,
            completedAt = task.completedAt,
            completedByUserId = task.completedByUserId,
            outcome = task.outcome,
            outcomeNotes = task.outcomeNotes,
            autoGenerated = task.autoGenerated,
            source = task.source,
            isOverdue = task.isOverdue(),
            isDueToday = task.isDueToday(),
            createdAt = task.createdAt,
            updatedAt = task.updatedAt
        )
    }
}

data class TaskStatsResponse(
    val totalPending: Long,
    val totalInProgress: Long,
    val totalOverdue: Long,
    val totalDueToday: Long,
    val completedThisWeek: Long
) {
    companion object {
        fun from(stats: TaskStats): TaskStatsResponse = TaskStatsResponse(
            totalPending = stats.totalPending,
            totalInProgress = stats.totalInProgress,
            totalOverdue = stats.totalOverdue,
            totalDueToday = stats.totalDueToday,
            completedThisWeek = stats.completedThisWeek
        )
    }
}

data class MyTasksResponse(
    val stats: TaskStatsResponse,
    val overdue: List<MemberTaskResponse>,
    val dueToday: List<MemberTaskResponse>,
    val upcoming: List<MemberTaskResponse>
)
